services:
  frontend-app:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    restart: unless-stopped
