services:
  frontend-app:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: 'http://localhost:8080/api'
    ports:
      - "8081:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_BASE_URL: 'http://localhost:8080/api'
    restart: unless-stopped