version: '3.8'

#services:
#    php-apache-react:
#        container_name: php-apache-react
#        build:
#            context: php
#        ports:
#            - '8081:80'
#        volumes:
#            - ./:/var/www/react_docker
#            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf

services:
    nginx-react:
        container_name: nginx-react
        build: .
        volumes:
            - ./build:/etc/nginx/templates
            - ./:/var/www/react_docker
        ports:
            - "8081:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
