version: '3.8'

services:
  nginx:
    container_name: nginx
    build: .
#    volumes:
#      - ./build:/var/www/react_docker
#      - ./:/var/www/react_docker
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

#  deploy:
#    container_name: deploy
#    build: .docker/deploy
#    volumes:
#      - ./:/var/www/react_docker
#    command:
#      - cp .docker/nginx/default.conf /etc/nginx/conf.d
#    depends_on:
#      - deploy
